services:
  app:
    build:
      context: ./SCVSupermercado
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://scvsupermercado:3306/SCVSupermercado?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
      DB_PLATFORM: org.hibernate.dialect.MySQLDialect
    depends_on:
      scvsupermercado:
        condition: service_healthy

  scvsupermercado:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: SCVSupermercado     
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
